spring:
  application:
    name: first-server
  devtools:
    add-properties: false
server:
  port: 8081

eureka:
  instance:
    hostname: server
    appname: eureka-server
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://server2:8082/eureka/