spring:
  application:
    name: git-config-server

  cloud:
    config:
      server:
        git:
          uri: https://github.com/syl-skty/spring-cloud
          search-paths: /config-file


server:
  port: 6060