spring:
  application:
    name: second-server
  devtools:
    add-properties: false

server:
  port: 8082

eureka:
  instance:
    hostname: server2
    appname: eureka-server
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://server:8081/eureka/